In [1]:
import numpy as np

### Array Oluşturmak

In [4]:
dizi = np.array([10, 20, 30, 40, 50])
print(f"Dizi: {dizi}")
print(f"Toplam: {dizi.sum()}")
print(f"Ortalama: {dizi.mean()}")


Dizi: [10 20 30 40 50]
Toplam: 150
Ortalama: 30.0


### Martris işlemlerde Transpoze almak

In [6]:
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matris:")
print(matris)
print(f"Transpozu:")
print(matris.T)


Matris:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpozu:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Rastgele Sayı Üretmek

In [11]:
rastgele = np.random.rand(5)
print(f"Rastgele Değerler: {rastgele}")


Rastgele Değerler: [0.0597412  0.89549643 0.84495073 0.19089195 0.77479435]


### Veri Normalizasyonu

In [12]:
veriler = np.array([100, 200, 300, 400, 500])
normalizasyon = (veriler - veriler.min()) / (veriler.max() - veriler.min())
print(f"Normalize Edilmiş Veriler: {normalizasyon}")


Normalize Edilmiş Veriler: [0.   0.25 0.5  0.75 1.  ]
